## DATA PREPROCESSING AND DATA CLEANING

In [1]:
# Import the necessary libraries.
import pandas as pd
import numpy as np

In [2]:
# Avoid unnecessary warnings, (EX: software updates, version mismatch, and so on.)
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('weather_data.csv')
df.head()

,City,Temperature_Celsius,Wind_Speed_ms,Latitude,Longitude,Description,Country
0,Paris,10.46,2.06,48.8534,2.3488,clear sky,France
1,Dubai,29.32,3.09,25.2582,55.3047,clear sky,United Arab Emirates
2,Madrid,9.97,3.60,40.4165,-3.7026,clear sky,Spain
3,Tokyo,21.58,2.06,35.6895,139.6917,broken clouds,Japan
4,Amsterdam,8.00,3.58,52.3740,4.8897,clear sky,Netherlands

In [4]:

# Transform the columns value(ex: int to str, str to int) for classification purpose.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

var = ['City','Description','Country']
  
for i in var:
    df[i] = le.fit_transform(df[i]).astype(int)

In [5]:
# Check the top5 values
df.head()

,City,Temperature_Celsius,Wind_Speed_ms,Latitude,Longitude,Description,Country
0,61,10.46,2.06,48.8534,2.3488,1,13
1,18,29.32,3.09,25.2582,55.3047,1,43
2,44,9.97,3.60,40.4165,-3.7026,1,37
3,88,21.58,2.06,35.6895,139.6917,0,22
4,1,8.00,3.58,52.3740,4.8897,1,27

In [6]:
# Check the bottom five values.
df.tail()

,City,Temperature_Celsius,Wind_Speed_ms,Latitude,Longitude,Description,Country
95,66,26.87,6.69,18.5818,-68.4043,2,10
96,25,24.06,0.97,25.2819,110.2864,1,7
97,26,28.00,2.49,21.0245,105.8412,1,46
98,13,19.42,4.63,30.0626,31.2497,1,11
99,55,28.01,2.76,23.6139,58.5922,0,28

In [7]:
# Check the dimension of our datasets
df.shape

(100, 7)

In [8]:
# Check the dataset size 
df.size

700

In [9]:
# Check the columns of dataset
df.columns

Index(['City', 'Temperature_Celsius', 'Wind_Speed_ms', 'Latitude', 'Longitude',
       'Description', 'Country'],
      dtype='object')

In [10]:
# To know the information of our datsets
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City                 100 non-null    int64
 1   Temperature_Celsius  100 non-null    float64
 2   Wind_Speed_ms        100 non-null    float64
 3   Latitude             100 non-null    float64
 4   Longitude            100 non-null    float64
 5   Description          100 non-null    int64
 6   Country              100 non-null    int64
dtypes: float64(4), int64(3)
memory usage: 5.6 KB

In [11]:
# Check the unique columns of our specific column
df['Description'].unique()

array([ 1,  0, 11, 10,  9,  6,  2,  7,  8,  5,  3,  4, 12])

In [12]:
# Check the value is null or notnull
df.isnull().head()

,City,Temperature_Celsius,Wind_Speed_ms,Latitude,Longitude,Description,Country
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False

In [13]:
# Remove the null value
df = df.dropna()

In [14]:
# Describe the datasets into stastical point of view
df.describe()

,City,Temperature_Celsius,Wind_Speed_ms,Latitude,Longitude,Description,Country
count,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000
mean,49.500000,18.861700,3.59920,31.249418,18.550782,3.840000,24.620000
std,29.011492,7.017078,2.66491,19.451234,75.876596,3.963775,14.218909
min,0.000000,5.290000,0.45000,-34.613200,-157.858300,0.000000,0.000000
25%,24.750000,13.825000,1.54000,23.489600,-8.741575,1.000000,13.000000
50%,49.500000,18.005000,2.92500,35.173650,18.552400,1.000000,22.500000
75%,74.250000,26.120000,4.63000,43.825025,74.154525,9.000000,37.000000
max,99.000000,32.350000,14.75000,59.437000,151.207300,12.000000,46.000000

In [15]:
# Check the relation between each individual columns
df.corr().head()

,City,Temperature_Celsius,Wind_Speed_ms,Latitude,Longitude,Description,Country
City,1.000000,-0.082250,-0.053903,0.002290,-0.082659,0.034960,-0.060727
Temperature_Celsius,-0.082250,1.000000,0.084105,-0.563209,0.078445,-0.019819,0.136983
Wind_Speed_ms,-0.053903,0.084105,1.000000,-0.109404,-0.559044,-0.043158,0.034161
Latitude,0.002290,-0.563209,-0.109404,1.000000,-0.065362,0.016487,0.147571
Longitude,-0.082659,0.078445,-0.559044,-0.065362,1.000000,0.156829,-0.115786

In [16]:
# Check the events for specific columns
pd.crosstab(df["Wind_Speed_ms"], df["Wind_Speed_ms"]).head()

Wind_Speed_ms,0.45,0.51,0.89,0.97,1.03,1.06,1.14,1.24,1.33,1.40,...,5.83,6.00,6.17,6.69,7.20,7.60,8.23,9.26,12.52,14.75
Wind_Speed_ms,,,,,,,,,,,,,,,,,,,,,
0.45,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.51,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.89,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.97,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1.03,0,0,0,0,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# Ascending the value of specific columns
df.groupby(["Latitude","Longitude"]).groups

{(-34.6132, -58.3772): [77], (-33.8679, 151.2073): [21], (-33.4569, -70.6483): [87], (-23.5475, -46.6361): [53], (-22.9028, -43.2075): [65], (-12.0432, -77.0282): [78], (1.2897, 103.8501): [10], (1.4655, 103.7578): [86], (3.1431, 101.6865): [35], (8.0, 98.25): [79], (10.75, 106.6667): [84], (13.75, 100.5167): [32], (18.5818, -68.4043): [95], (19.0144, 72.8479): [94], (19.4285, -99.1277): [55], (20.6274, -87.0799): [85], (21.0245, 105.8412): [97], (21.1743, -86.8466): [69], (21.3069, -157.8583): [66], (21.4267, 39.8261): [83], (22.2006, 113.5461): [68], (22.2769, 113.5678): [93], (22.2855, 114.1577): [16], (22.5455, 114.0683): [49], (23.1167, 113.25): [44], (23.6139, 58.5922): [99], (24.4667, 54.3667): [37], (24.6877, 46.7219): [89], (25.0478, 121.5319): [27], (25.2582, 55.3047): [1], (25.2819, 110.2864): [96], (25.2867, 51.5333): [71], (25.3573, 55.4033): [72], (25.7743, -80.1937): [34], (27.0998, -82.4543): [36], (28.0836, -80.6081): [23], (28.5383, -81.3792): [24], (28.6667, 77.2167): [80], (30.0626, 31.2497): [98], (31.2222, 121.4581): [42], (31.6315, -8.0083): [90], (31.769, 35.2163): [63], (32.0833, 34.8): [40], (33.6064, 130.4181): [60], (33.7104, 73.1338): [70], (34.0522, -118.2437): [18], (34.257, -85.1647): [6], (34.6937, 135.5022): [15], (35.0211, 135.7538): [26], (35.1028, 129.0403): [59], (35.2445, 25.0929): [81], (35.6895, 139.6917): [3], (36.175, -115.1372): [33], (36.4408, 28.2225): [73], (36.7741, 30.7178): [56], (37.2303, 28.3557): [92], (37.3824, -5.9761): [52], (37.5683, 126.9778): [13], (37.7021, -121.9358): [14], (37.7749, -122.4194): [41], (37.9795, 23.7162): [30], (38.7167, -9.1333): [19], (39.3333, -0.8333): [54], (39.5694, 2.6502): [51], (39.9075, 116.3972): [58], (40.4165, -3.7026): [2], (40.6403, 22.9439): [76], (40.7143, -74.006): [7], (41.0351, 28.9833): [22], (41.1496, -8.611): [62], (41.3888, 2.159): [8], (41.6941, 44.8337): [88], (43.0642, 141.3469): [57], (43.7001, -79.4163): [29], (43.7667, 11.25): [28], (44.0, 7.25): [46], (44.4667, 11.4333): [75], (45.4167, 11.0333): [74], (45.4643, 9.1895): [12], (45.5088, -73.5878): [67], (47.3667, 8.55): [31], (47.498, 19.0399): [48], (47.5001, -120.5015): [47], (48.1374, 11.5755): [11], (48.2085, 16.3721): [17], (48.8534, 2.3488): [0], (49.2497, -123.1193): [50], (50.0833, 19.9167): [64], (50.088, 14.4208): [20], (50.1167, 8.6833): [25], (50.8504, 4.3488): [39], (51.5085, -0.1257): [9], (52.2298, 21.0118): [43], (52.374, 4.8897): [4], (52.5244, 13.4105): [5], (54.6892, 25.2798): [91], (55.6759, 12.5655): [45], (55.9521, -3.1965): [61], (59.3326, 18.0649): [38], (59.437, 24.7535): [82]}

In [18]:
# Check the value counts for specific columns
df["Description"].value_counts()

Description
1     40
10    15
0     13
9     10
2      9
6      6
11     1
7      1
8      1
5      1
3      1
4      1
12     1
Name: count, dtype: int64

In [19]:
# Check the specific column catagorical distribution
pd.Categorical(df["Description"]).describe()

            counts  freqs
categories
0               13   0.13
1               40   0.40
2                9   0.09
3                1   0.01
4                1   0.01
5                1   0.01
6                6   0.06
7                1   0.01
8                1   0.01
9               10   0.10
10              15   0.15
11               1   0.01
12               1   0.01

In [20]:
# Check if the value is duplicated or not
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [21]:
# Calculate the total number of duplicated values
sum(df.duplicated())

0

In [22]:
# Remove the duplicate values
df=df.drop_duplicates()

In [23]:
# Calculate the total number of duplicated values
sum(df.duplicated())

0